# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'bbp(2)(114515eb-8df4-4543-b27c-be7cf14bfff9)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account get-access-token --resource="https://management.azure.com/"'
     
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
